[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mpipy"
version = "0.0.1"
description = "Minimal MPI-style runtime in pure Python"
readme = "notes.md"
requires-python = ">=3.9"
license = {text = "MIT"}
